# Generated by Django 4.2.3 on 2023-07-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1024)),
                ('section', models.CharField(max_length=30)),
            ],
        ),
    ]
