# Generated by Django 4.2.3 on 2023-08-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('abstract', models.TextField(default='')),
                ('url', models.URLField(max_length=1024)),
                ('img_url', models.URLField(default='', max_length=1024)),
                ('section', models.CharField(max_length=30)),
                ('paper', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(max_length=1024)),
                ('section', models.CharField(max_length=30)),
            ],
        ),
    ]
