# Generated by Django 4.2.3 on 2023-07-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="abstract",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="img_url",
            field=models.URLField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="article",
            name="paper",
            field=models.CharField(default="", max_length=100),
        ),
    ]
