# Generated by Django 4.2.3 on 2023-07-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_abstract_article_img_url_article_paper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
